name: Release Log

on:
  push:
    tags:
      - 'v*'
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Read Release.md
        id: read_release
        run: |
          TODAY=$(date '+%Y-%m-%d')

          echo "RELEASE_BODY<<EOF" >> $GITHUB_ENV

          echo  -e "\`$TODAY\`\n" >> $GITHUB_ENV

          cat Release.md >> $GITHUB_ENV

          echo "EOF" >> $GITHUB_ENV

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          tag_name: ${{ github.ref }}
          body: ${{ env.RELEASE_BODY }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
