name: Main

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Read Release.md
        id: read_release
        run: |
          echo "RELEASE_BODY<<EOF" >> $GITHUB_ENV
          cat Release.md >> $GITHUB_ENV
          echo -e "\n## 新版本发布！\n请查看 [变更日志](CHANGELOG.md) 以获取更多信息。" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v0.0.2
          body: ${{ env.RELEASE_BODY }}
          files: |
            Release.md
            LICENSE
